//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointofSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_DETAIL
    {
        public int SalesDetail_ID { get; set; }
        public Nullable<int> Sales_ID { get; set; }
        public Nullable<int> PD_ID { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> LineTotal { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual SALE SALE { get; set; }
    }
}
